### ISSUE TITLE
feat: custom-fetch api 세팅

### ISSUE THREAD

**Issue by minsu-zip** [YAPP-Github/24th-Web-Team-3-FE#16]
## 👷‍♂️ 어떤 기능인가요?

api 함수 호출 시 fetch를 사용하도록 전역 설정

why: App router 공식문서에서는 fetch를 권장하고 있습니다.(서버쪽 캐싱 관련을 확장해서 제공)  fetch가 아닌 라이브러리를 사용하게 된다면 캐싱을 컨트롤 해야하는 상황이 생깁니다.
물론 흔한 axios를 사용하고 캐싱을 컨트롤하는게 훨씬 쉽고 직관적이나, 이번 기회에 기본 옵션인 fetch에서 어떤 옵션이 있고, 어떤 부가적인 기능이 필요한지 학습겸 fetch를 적용해보기로했습니다.

## ✅ 작업 상세 내용

> 작업할 Todos를 적어주세요

- [ ] afetch api 세팅

## 📁 참고할만한 자료(선택)

[Next.js App Router로 제품 만들기: 이제 더 이상 Axios를 쓰지 않기로 했습니다](https://blog.deercorp.com/next-js-app-router-and-fetch-library/)

위 아티클 관련 부가 정보
- https://return-fetch.myeongjae.kim/?ref=blog.deercorp.com
- https://github.com/deer-develop/return-fetch

**Comment by MayOwall** [comment]
feat인가요 setting인가요? 제목과 label이 달라서 뭐가 맞는지 궁금합니다~
